language: java
sudo: false
script: mvn clean verify
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
cache:
  directories:
    - '$HOME/.m2/repository'
after_success:
  - bash <(curl -s https://codecov.io/bash)
