language: java

env:
  global:
    - JABBA_HOME=$HOME/.jabba

cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.jabba"

before_cache:
  - rm -rf "$HOME/.m2/repository/de/bmarwell/ffb"

matrix:
  include:
    - os: linux
      sudo: false
      env:
        - TRAVIS_JDK=adopt@1.11.0-6
    - os: linux
      sudo: false
      env:
        - TRAVIS_JDK=adopt-openj9@1.11.0-6
    - os: linux
      sudo: false
      env:
        - TRAVIS_JDK=openjdk@1.14.0

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.11.0/install.sh | bash && . $JABBA_HOME/jabba.sh; fi

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then $JABBA_HOME/bin/jabba install $TRAVIS_JDK; jabba use $TRAVIS_JDK; fi
  - java -version

script:
  - ./mvnw --batch-mode clean verify -Pdocs

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl "https://oss.sonatype.org/service/local/repositories/releases/content/com/codacy/codacy-coverage-reporter/2.0.2/codacy-coverage-reporter-2.0.2-assembly.jar" -o ~/codacy.coverage-reporter-2.0.2-assembly.jar)
  - bash <(java -cp ~/codacy.coverage-reporter-2.0.2-assembly.jar com.codacy.CodacyCoverageReporter -l Java -r target/site/jacoco/jacoco.xml --projectToken "${CODACY_PROJECT_TOKEN}")
